using Microsoft.AspNetCore.Mvc;
using PropertyPlatform.Core;
using PropertyPlatform.Infrastructure.Models;

namespace PropertyPlatform.API.Controllers;

[ApiController]
[Route("api/[controller]")]
public sealed class PropertiesController : ControllerBase
{
    private readonly PropertyRepository _propertyRepository;

    public PropertiesController(PropertyRepository propertyRepository)
    {
        _propertyRepository = propertyRepository;
    }

    [HttpPost]
    public async Task<IActionResult> CreateProperty(CreatePropertyRequest request)
    {
        var property = new Property(
            0, // ID will be auto-generated by database
            request.Title,
            request.Description,
            request.VideoUrl,
            request.Price,
            request.AdvancePayment,
            request.Location,
            request.IsAvailable,
            request.Status,
            request.DealerId
        );

        await _propertyRepository.CreatePropertyAsync(property);
        return CreatedAtAction(nameof(GetPropertyById), new { id = property.Id }, property);
    }

    [HttpGet]
    public async Task<IActionResult> GetProperties(decimal? minPrice, decimal? maxPrice, string? status, string? location)
    {
        var properties = await _propertyRepository.GetPropertiesAsync(minPrice, maxPrice, status, location);
        return Ok(properties);
    }

    [HttpGet("{id}")]
    public async Task<IActionResult> GetPropertyById(long id)
    {
        var property = await _propertyRepository.GetPropertyByIdAsync(id);
        return property is not null ? Ok(property) : NotFound();
    }

    [HttpPut("{id}")]
    public async Task<IActionResult> UpdateProperty(long id, UpdatePropertyRequest request)
    {
        var existing = await _propertyRepository.GetPropertyByIdAsync(id);
        if (existing is null)
        {
            return NotFound();
        }

        var updatedProperty = new Property(
            id,
            request.Title ?? existing.Title,
            request.Description ?? existing.Description,
            request.VideoUrl ?? existing.VideoUrl,
            request.Price ?? existing.Price,
            request.AdvancePayment ?? existing.AdvancePayment,
            request.Location ?? existing.Location,
            request.IsAvailable ?? existing.IsAvailable,
            request.Status ?? existing.Status,
            request.DealerId ?? existing.DealerId
        );

        var updated = await _propertyRepository.UpdatePropertyAsync(id, updatedProperty);
        return updated ? Ok(updatedProperty) : NotFound();
    }

    [HttpDelete("{id}")]
    public async Task<IActionResult> DeleteProperty(long id)
    {
        var deleted = await _propertyRepository.DeletePropertyAsync(id);
        return deleted ? NoContent() : NotFound();
    }
}
